---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
  - name: Install Apache
  ¦ dnf:
  ¦ ¦ name:
  ¦ ¦ -  httpd
  ¦ ¦ -  ntpstat
  ¦ ¦ #state: latest
  ¦ when: ansible_os_family == "RedHat"

  - name: Install Apache
  ¦ apt:
  ¦ ¦ name:
  ¦ ¦ - apache2
  ¦ ¦ - ntpdate
  ¦ ¦ #state: latest
  ¦ when: ansible_os_family == "Debian"
