---

- name: windows rolling update

  hosts: windows 

  tasks:

    - name: Install all critical and security updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
        reboot: true
        log_path: C:\ansible.txt
